from utils.plot_config import PlotConfig

base_config = {
    "base_lin_vel": PlotConfig(
        title="Linear Velocity",
        xlabel="Time [s]",
        ylabel="Velocity [m/s]",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
        keys=["x", "y", "z"],
    ),
    "base_ang_vel": PlotConfig(
        title="Angular Velocity",
        xlabel="Time [s]",
        ylabel="Angular Velocity [rad/s]",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
        keys=["x", "y", "z"],
    ),
    "projected_gravity": PlotConfig(
        title="Projected Gravity",
        xlabel="Time [s]",
        ylabel="Projected Gravity",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
        keys=["x", "y", "z"],
    ),
    "velocity_commands": PlotConfig(
        title="Velocity Commands",
        xlabel="Time [s]",
        ylabel="Velocity Commands [m/s, rad/s]",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
        keys=["x", "y", "yaw"],
    ),
    "joint_pos": PlotConfig(
        title="Joint Position",
        xlabel="Time [s]",
        ylabel="Joint Position [rad]",
        num_subplots=3,
        subplot_kwargs={"sharex": True},
    ),
    "joint_vel": PlotConfig(
        title="Joint Velocity",
        xlabel="Time [s]",
        ylabel="Joint Velocity [rad/s]",
        num_subplots=3,
        subplot_kwargs={"sharex": True},
    ),
    "last_actions": PlotConfig(
        title="Last Actions",
        xlabel="Time [s]",
        ylabel="Action [rad]",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
    ),
    "body_lin_acc": PlotConfig(
        title="Body Acceleration",
        xlabel="Time [s]",
        ylabel="Acceleration [m/s^2]",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
        keys=["x", "y", "z"]
    ),
    "actions": PlotConfig(
        title="Actions",
        xlabel="Time [s]",
        ylabel="Action [rad]",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
    ),
    "net_wrench": PlotConfig(
        title="External Wrench",
        xlabel="Time [s]",
        ylabel="Force/Torque [N, Nm]",
        num_subplots=2,
        subplot_kwargs={"sharex": True},
        keys=["x", "y", "z", "x", "y", "z",],
        linestyles=["solid", "solid", "solid", "solid", "solid", "solid"],
        colors=["tab:blue", "tab:orange", "tab:green", "tab:blue", "tab:orange", "tab:green"],
    ),
    "ground_reaction_forces": PlotConfig(
        title="Ground Reaction Force",
        xlabel="Time [s]",
        ylabel="Force [N]",
        num_subplots=1,
        subplot_kwargs={"sharex": True},
        linestyles=["solid", "solid", "solid", "solid", "dashed", "dashed", "dashed", "dashed"],
        colors=["tab:blue", "tab:orange", "tab:green", "tab:red", "tab:blue", "tab:orange", "tab:green", "tab:red"],
    ),
    "force_bool": PlotConfig(
        title="Force Boolean",
        xlabel="Time [s]",
        ylabel="State",
        num_subplots=1,
        keys=["true", "est"],
        linestyles=["solid", "dashed"],
        colors=["tab:blue", "tab:orange"],
    ),
    "force_norm": PlotConfig(
        title="Force Norm",
        xlabel="Time [s]",
        ylabel="Force [N]",
        num_subplots=1,
        keys=["true", "est"],
        linestyles=["solid", "dashed"],
        colors=["tab:blue", "tab:orange"],
    ),
    "force_vec": PlotConfig(
        title="Force Vector",
        xlabel="Time [s]",
        ylabel="Force [N]",
        num_subplots=1,
        keys=["x", "y", "z", "x_est", "y_est", "z_est"],
        linestyles=["solid", "solid", "solid", "dashed", "dashed", "dashed"],
        colors=["tab:blue", "tab:orange", "tab:green", "tab:blue", "tab:orange", "tab:green"],
    ),
}